name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'


    - name: Build with Gradle
      run: chmod 777 *
      
    # Build the project
    - name: Build with Gradle
      run: ./gradlew clean build

    # Archive build artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*
